package cfg

import (
	"fmt"
	"reflect"
	"regexp"
	"strconv"
	"strings"
)

// HMOptionsNix renders the home-manager option declarations for the
// devcell.toml schema by reflecting over CellConfig. The generated file
// (nix/home-manager/options.nix, written by `task hm:generate`) is what
// keeps `devcell.*` options in lockstep with the Go schema — hand-editing
// it would reintroduce drift, hence the DO NOT EDIT header.
//
// Mapping rules:
//   - string → types.str, int → types.int, bool / *bool → types.bool
//   - []string → listOf str, map[string]string → attrsOf str
//   - struct field → plain nested attrset (a TOML table the user sets
//     directly: devcell.llm.system_prompt = "...")
//   - []struct / map[string]struct → listOf/attrsOf (submodule { ... })
//
// Every leaf is nullOr with default null: unset options never reach the
// rendered TOML, so absence semantics (e.g. modules unset vs modules = [])
// match a hand-written devcell.toml.
func HMOptionsNix() string {
	var b strings.Builder
	b.WriteString(`# Code generated by hmoptgen from internal/cfg.CellConfig; DO NOT EDIT.
# Regenerate: task hm:generate (runs automatically as a dep of cell:build).
# Each leaf mirrors one devcell.toml key; null (the default) omits the key.
{ lib }:
let
  inherit (lib) mkOption types;
  opt = type: mkOption {
    type = types.nullOr type;
    default = null;
  };
in
`)
	writeSection(&b, reflect.TypeOf(CellConfig{}), 0)
	b.WriteString("\n")
	return b.String()
}

// writeSection emits a struct as a nix attrset of options, one line per leaf.
func writeSection(b *strings.Builder, t reflect.Type, depth int) {
	pad := strings.Repeat("  ", depth)
	b.WriteString("{\n")
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		key := tomlKey(f)
		if key == "-" || f.Tag.Get("hm") == "-" {
			continue
		}
		ft := f.Type
		if ft.Kind() == reflect.Struct {
			fmt.Fprintf(b, "%s  %s = ", pad, nixAttrName(key))
			writeSection(b, ft, depth+1)
			b.WriteString(";\n")
			continue
		}
		fmt.Fprintf(b, "%s  %s = opt %s;\n", pad, nixAttrName(key), nixType(ft, depth+1))
	}
	fmt.Fprintf(b, "%s}", pad)
}

// nixType maps a Go type to a nix `types.*` expression. Composite types are
// parenthesized so they slot into `opt (...)` unambiguously.
func nixType(t reflect.Type, depth int) string {
	switch t.Kind() {
	case reflect.String:
		return "types.str"
	case reflect.Bool:
		return "types.bool"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "types.int"
	case reflect.Float32, reflect.Float64:
		return "types.float"
	case reflect.Pointer:
		return nixType(t.Elem(), depth)
	case reflect.Slice:
		return fmt.Sprintf("(types.listOf %s)", elemType(t.Elem(), depth))
	case reflect.Map:
		return fmt.Sprintf("(types.attrsOf %s)", elemType(t.Elem(), depth))
	default:
		panic(fmt.Sprintf("hmoptions: unsupported Go type %s — extend nixType", t))
	}
}

// elemType renders a slice/map element type; structs become submodules.
func elemType(t reflect.Type, depth int) string {
	if t.Kind() != reflect.Struct {
		return strings.TrimSuffix(strings.TrimPrefix(nixType(t, depth), "("), ")")
	}
	var b strings.Builder
	b.WriteString("(types.submodule {\n")
	pad := strings.Repeat("  ", depth)
	fmt.Fprintf(&b, "%s  options = ", pad)
	writeSection(&b, t, depth+1)
	b.WriteString(";\n")
	fmt.Fprintf(&b, "%s})", pad)
	return b.String()
}

var nixIdentRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_'-]*$`)

// nixAttrName quotes TOML keys that aren't valid nix identifiers (e.g. "2fa").
func nixAttrName(key string) string {
	if nixIdentRe.MatchString(key) {
		return key
	}
	return strconv.Quote(key)
}

// tomlKey resolves the TOML key for a struct field: the tag's name part,
// falling back to the lowercased field name (BurntSushi's untagged default
// is a case-insensitive field match; devcell configs use lowercase keys).
func tomlKey(f reflect.StructField) string {
	tag := f.Tag.Get("toml")
	if tag == "" {
		return strings.ToLower(f.Name)
	}
	name, _, _ := strings.Cut(tag, ",")
	if name == "" {
		return strings.ToLower(f.Name)
	}
	return name
}
