package cfg

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

// SchemaBase is the site path under which every schema version is served.
// Each version lives in its own directory, so configs can pin the schema
// matching their cell binary:
//
//	https://devcell.sh/schema/<version>/devcell.json             the config schema
//	https://devcell.sh/schema/<version>/devcell-sh/home/*.json   the home catalog
//
// Astro copies web/public/ verbatim, so web/public/schema/<version>/ is the
// on-disk mirror. DefaultSchemaVersion is what main commits (regenerated by
// the schema-generate pre-commit hook and cell:build); a release can publish
// its own tag alongside it later. Reference it from a config with
// `#:schema https://devcell.sh/schema/v0.0.0/devcell.json` (taplo / Even Better TOML).
const SchemaBase = "https://devcell.sh/schema"

// DefaultSchemaVersion is the version published from main (unreleased).
const DefaultSchemaVersion = "v0.0.0"

// SchemaURLFor returns the published URL of the config schema for a version.
func SchemaURLFor(version string) string {
	return SchemaBase + "/" + normalizeVersion(version) + "/devcell.json"
}

// CatalogURLFor returns the published directory of the home flake's
// module/stack/package catalog for a version (see internal/nixhome.CatalogPath).
func CatalogURLFor(version string) string {
	return SchemaBase + "/" + normalizeVersion(version) + "/devcell-sh/home"
}

func normalizeVersion(v string) string {
	if v == "" {
		return DefaultSchemaVersion
	}
	return v
}

// SchemaOptions carries the inputs JSONSchema cannot derive from CellConfig.
type SchemaOptions struct {
	Version      string            // published version (release tag); empty means DefaultSchemaVersion
	Descriptions map[string]string // "StructName.FieldName" → text; see FieldComments
	Modules      []string          // module names from the home catalog, offered as completions
	Stacks       []string          // stack names from the home catalog, offered as completions
}

// LoadCatalog fills Modules and Stacks from a directory holding the
// published catalog (modules.json, stacks.json). A missing directory or file
// is not an error: the schema is still valid, just without completions.
func (o *SchemaOptions) LoadCatalog(dir string) error {
	for _, f := range []struct {
		name string
		dst  *[]string
	}{{"modules.json", &o.Modules}, {"stacks.json", &o.Stacks}} {
		raw, err := os.ReadFile(filepath.Join(dir, f.name))
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		var m map[string]json.RawMessage
		if err := json.Unmarshal(raw, &m); err != nil {
			return fmt.Errorf("jsonschema: %s: %w", f.name, err)
		}
		names := make([]string, 0, len(m))
		for k := range m {
			names = append(names, k)
		}
		sort.Strings(names)
		*f.dst = names
	}
	return nil
}

// JSONSchema renders the devcell.toml JSON Schema (draft 2020-12) by
// reflecting over CellConfig, the same source of truth HMOptionsNix uses
// for nix/home-manager/options.nix. `task schema:generate` (a dep of
// cell:build) writes web/public/schema/devcell.json from it.
//
// opts.Descriptions maps "StructName.FieldName" to a description;
// FieldComments builds it from the source comments in cfg.go. Catalog names
// become non-strict completions (examples, never enum: a custom home can add
// modules and stacks the published catalog does not know), and package lists
// carry the loader's nix attribute pattern with a link to search.nixos.org.
//
// Mapping rules:
//   - string → string, int → integer, float → number, bool / *bool → boolean
//   - []T → array of T, map[string]T → object with additionalProperties T
//   - struct → closed object (additionalProperties: false), so unknown keys
//     get flagged in the editor the way checkUnknownKeys flags them at load
//   - a key listed in Deprecations is marked deprecated, with the migration
//     message appended to its description
//
// Fields tagged toml:"-" are not user-facing and are skipped. The hm:"-"
// tag is nix-specific and ignored here: those keys are still valid TOML.
func JSONSchema(opts SchemaOptions) ([]byte, error) {
	deprecated := make(map[string]Deprecation, len(Deprecations))
	for _, d := range Deprecations {
		deprecated[strings.Join(d.Path, ".")] = d
	}
	g := schemaGen{descs: opts.Descriptions, deprecated: deprecated}

	root := g.object(reflect.TypeOf(CellConfig{}), nil)
	applyHints(root, opts)
	version := normalizeVersion(opts.Version)
	root["$schema"] = "https://json-schema.org/draft/2020-12/schema"
	root["$id"] = SchemaURLFor(version)
	root["version"] = version
	root["title"] = "devcell.toml"
	root["description"] = "devcell project configuration (.devcell.toml) and global defaults (~/.config/devcell/devcell.toml). Generated from internal/cfg.CellConfig; do not edit."

	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("jsonschema: %w", err)
	}
	return append(out, '\n'), nil
}

// applyHints decorates the generated tree with catalog completions, package
// name patterns, and taplo key links. Paths are TOML key paths.
func applyHints(root map[string]any, opts SchemaOptions) {
	catalog := CatalogURLFor(opts.Version)
	at := func(path ...string) map[string]any {
		cur := root
		for _, p := range path {
			cur = cur["properties"].(map[string]any)[p].(map[string]any)
		}
		return cur
	}
	link := func(s map[string]any, url string) {
		s["x-taplo"] = map[string]any{"links": map[string]any{"key": url}}
	}

	modules := at("cell", "modules")
	link(modules, catalog+"/modules.json")
	if len(opts.Modules) > 0 {
		modules["items"].(map[string]any)["examples"] = opts.Modules
	}
	stack := at("cell", "stack")
	link(stack, catalog+"/stacks.json")
	if len(opts.Stacks) > 0 {
		stack["examples"] = opts.Stacks
	}

	for _, path := range [][]string{
		{"cell", "packages"},
		{"packages", "nix", "stable"},
		{"packages", "nix", "unstable"},
		{"packages", "nix", "edge"},
	} {
		s := at(path...)
		s["items"].(map[string]any)["pattern"] = validNixAttr.String()
		link(s, "https://search.nixos.org/packages")
	}
}

type schemaGen struct {
	descs      map[string]string
	deprecated map[string]Deprecation
}

// object renders a struct as a closed JSON object. path is the TOML key
// path of the struct itself, used to look up deprecations of its fields.
func (g schemaGen) object(t reflect.Type, path []string) map[string]any {
	props := make(map[string]any, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		key := tomlKey(f)
		if key == "-" {
			continue
		}
		fieldPath := append(append([]string{}, path...), key)
		s := g.schema(f.Type, fieldPath)

		var desc string
		if d, ok := g.descs[t.Name()+"."+f.Name]; ok {
			desc = d
		}
		if d, ok := g.deprecated[strings.Join(fieldPath, ".")]; ok {
			s["deprecated"] = true
			note := "Deprecated: " + d.Message
			if d.Replacement != "" && d.Replacement != "(none)" {
				note += " (replacement: " + d.Replacement + ")"
			}
			if desc != "" {
				desc += ". " + note
			} else {
				desc = note
			}
		}
		if desc != "" {
			s["description"] = desc
		}
		props[key] = s
	}
	return map[string]any{
		"type":                 "object",
		"properties":           props,
		"additionalProperties": false,
	}
}

// schema maps a Go type to its JSON Schema fragment.
func (g schemaGen) schema(t reflect.Type, path []string) map[string]any {
	switch t.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Pointer:
		return g.schema(t.Elem(), path)
	case reflect.Slice:
		return map[string]any{"type": "array", "items": g.schema(t.Elem(), path)}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": g.schema(t.Elem(), path)}
	case reflect.Struct:
		return g.object(t, path)
	default:
		panic(fmt.Sprintf("jsonschema: unsupported Go type %s — extend schemaGen.schema", t))
	}
}

// FieldComments extracts struct field comments from Go source as a
// "StructName.FieldName" → text map. A trailing line comment wins over the
// doc comment above the field; fields with neither are absent.
func FieldComments(src []byte) (map[string]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("jsonschema: parse source: %w", err)
	}
	out := map[string]string{}
	ast.Inspect(file, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		for _, f := range st.Fields.List {
			text := commentText(f.Comment)
			if text == "" {
				text = commentText(f.Doc)
			}
			if text == "" {
				continue
			}
			for _, name := range f.Names {
				out[ts.Name.Name+"."+name.Name] = text
			}
		}
		return false
	})
	return out, nil
}

func commentText(cg *ast.CommentGroup) string {
	if cg == nil {
		return ""
	}
	return strings.TrimSpace(strings.Join(strings.Fields(cg.Text()), " "))
}
