package runner

import (
	"fmt"
	"os"
	"strings"
)

// RenderModulesOverlay returns a Nix module that flips
// `devcell.modules.<name>.enable = true` for each name in `modules`.
//
// Output is always a parseable nix attrset, even for an empty list (in which
// case the body is empty — home-manager treats it as a no-op).
//
// Module names are emitted as quoted strings (`"name"`) so that names with
// dashes ("yahoo-finance", "project-management") round-trip safely.
//
// The output is deterministic: same input → byte-identical output. This
// matters for build-cache hash stability — re-running `devcell build` with
// an unchanged `.devcell.toml` must not invalidate the previous nix store.
func RenderModulesOverlay(modules []string) string {
	var b strings.Builder
	b.WriteString("# Generated by devcell from .devcell.toml — do not edit.\n")
	b.WriteString("# Source of truth: [cell].modules in .devcell.toml + global ~/.config/devcell/devcell.toml.\n")
	b.WriteString("{ ... }: {\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "  devcell.modules.%q.enable = true;\n", m)
	}
	b.WriteString("}\n")
	return b.String()
}

// WriteModulesOverlay renders the overlay and writes it to outPath, replacing
// any existing file. Caller is responsible for creating outPath's parent dir.
func WriteModulesOverlay(modules []string, outPath string) error {
	content := RenderModulesOverlay(modules)
	return os.WriteFile(outPath, []byte(content), 0o644)
}
