package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"strconv"
	"strings"
	"syscall"

	_ "github.com/DimmKirr/devcell/api/swagger" // swagger docs (generated by swag init)
	"github.com/DimmKirr/devcell/internal/cell"
	"github.com/DimmKirr/devcell/internal/cfg"
	"github.com/DimmKirr/devcell/internal/config"
	"github.com/DimmKirr/devcell/internal/engine/docker"
	"github.com/DimmKirr/devcell/internal/logger"
	"github.com/DimmKirr/devcell/internal/serve"
	"github.com/DimmKirr/devcell/internal/telemetry"
	"github.com/spf13/cobra"
)

// @title DevCell Serve API
// @version 1.0
// @description DevCell Serve exposes an OpenAI-compatible HTTP API that proxies LLM requests to agent binaries (Claude Code, OpenCode) running inside a DevCell container.
// @description
// @description ## Why use this?
// @description
// @description Any tool that speaks the OpenAI protocol — Cursor, Continue, n8n, custom scripts, CI pipelines, the OpenAI Agents SDK — can target DevCell Serve as its backend. The server routes requests to the appropriate agent binary based on the `model` field — no SDK or CLI wrapper needed.
// @description
// @description ## Endpoints
// @description
// @description - **`POST /v1/chat/completions`** — Chat Completions API (the most widely supported OpenAI surface). Use this for traditional chat clients.
// @description - **`POST /v1/responses`** — Responses API (newer, used by OpenAI Agents SDK and n8n's "Message a Model" node). Same model routing as chat completions; stateless (no `previous_response_id` chain).
// @description - **`GET /v1/models`** — list available models discovered from installed agents.
// @description
// @description ## Quick start
// @description
// @description 1. Start the server: `cell serve` (or `cell serve --port 9090`)
// @description 2. The server prints an API key on startup. Set `DEVCELL_API_KEY` env var to use a fixed key.
// @description 3. Send requests with `Authorization: Bearer <key>` header.
// @description
// @description ## Model routing
// @description
// @description The `model` field selects which agent handles the prompt (same for both `/v1/chat/completions` and `/v1/responses`):
// @description - `"claude"`, `"default"` or `"anthropic"` → routes to the Claude Code CLI
// @description - `"opencode"` → routes to the OpenCode CLI
// @description - `"anthropic/sonnet"`, `"claude/claude-sonnet-4-5"` → Claude Code with a specific sub-model
// @description
// @description ## Limitations
// @description
// @description - **Streaming** (`"stream": true`) is supported for the claude agent on both `/v1/chat/completions` and `/v1/responses`. Opencode has no streaming surface and falls back to buffered.
// @description - **Background mode** (`"background": true`) is supported on `/v1/responses`: returns 202 with an id; poll `GET /v1/responses/{id}` until terminal, or cancel with `POST /v1/responses/{id}/cancel`. Jobs are in-memory and do not survive a serve restart. Combining `stream: true` with `background: true` returns 400.
// @description - **No tool calling.** The `tools` field is accepted for compatibility but never invokes a tool — the underlying CLI agents have their own internal tool loop.
// @description - **Stateless across requests.** `previous_response_id` is accepted and ignored; clients must re-send full conversation history each request.
// @description
// @description ## Reasoning effort
// @description
// @description Both endpoints honor the OpenAI `reasoning_effort` / `reasoning.effort` field (values: `low`, `medium`, `high`). It maps to the `claude --effort` CLI flag, controlling thinking budget on a per-request basis. Non-spec values (e.g. Claude's `xhigh`/`max`) are silently dropped.
// @description
// @description ## Debug logging
// @description
// @description By default the server logs only request metadata (method, path, status, duration) plus agent metadata at DEBUG level. Prompt and response bodies are **never** logged — they often contain secrets, PII, or large pasted content from upstream tools.
// @description
// @description Set `DEVCELL_LOG_PROMPTS=1` (combined with `LOG_LEVEL=info` or lower) to log the full assembled prompt and the model's reply for every `/v1/chat/completions` and `/v1/responses` request. Use only for debugging client integrations; do not leave on in production.
// @description
// @description ## Example curl
// @description
// @description Chat Completions:
// @description ```bash
// @description curl http://localhost:8484/v1/chat/completions \
// @description   -H "Authorization: Bearer $DEVCELL_API_KEY" \
// @description   -H "Content-Type: application/json" \
// @description   -d '{"model":"anthropic/sonnet","messages":[{"role":"user","content":"explain this repo"}]}'
// @description ```
// @description
// @description Responses API:
// @description ```bash
// @description curl http://localhost:8484/v1/responses \
// @description   -H "Authorization: Bearer $DEVCELL_API_KEY" \
// @description   -H "Content-Type: application/json" \
// @description   -d '{"model":"anthropic/sonnet","input":"explain this repo"}'
// @description ```
// @host localhost:8484
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Bearer token — set via DEVCELL_API_KEY env var or use the auto-generated key printed on startup. Format: `Bearer dcl-abc123...`

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start HTTP API server for LLM commands",
	Long: `Starts an OpenAI-compatible HTTP server that proxies requests
to LLM agent binaries (claude, opencode).

Endpoints:

    POST /v1/chat/completions  — OpenAI Chat Completions API
    POST /v1/responses         — OpenAI Responses API (newer; n8n, Agents SDK)
    GET  /v1/models            — list available models
    GET  /healthz              — health check (k8s convention)
    GET  /api/v1/health        — health check (REST convention)
    GET  /api/openapi.json     — OpenAPI spec
    GET  /swagger/             — Swagger UI

The model field selects the agent: "claude", "opencode", or
"anthropic/sonnet", "claude/claude-sonnet-4-5" (agent/submodel).

Chat Completions request:

    {"model": "anthropic/sonnet",
     "messages": [{"role": "user", "content": "explain this"}]}

Responses API request:

    {"model": "anthropic/sonnet", "input": "explain this"}

Streaming is supported on /v1/chat/completions and /v1/responses for
the claude agent (set "stream": true). Server-Sent Events are emitted
in the standard OpenAI shape: chat.completion.chunk frames terminated
by data: [DONE] for chat, response.<event-name> frames terminated by
response.completed for responses. Heartbeat ":keepalive" comments are
sent every 15s while idle so long-running agentic turns survive proxy
idle timeouts. Opencode has no streaming surface and falls back to
buffered. previous_response_id and tools are accepted but ignored.

Background (async) mode is supported on /v1/responses: set
"background": true to get back 202 + a stub response with an id and
status="in_progress". Poll GET /v1/responses/{id} until status is
terminal (completed | failed | cancelled). Cancel an in-progress job
with POST /v1/responses/{id}/cancel. Jobs live in process memory only —
they do NOT survive a serve restart. Terminal jobs are evicted after
1h. Combining stream=true with background=true returns 400.

The claude binary is invoked with --dangerously-skip-permissions (same
default cell claude uses) — without it any tool call would block on the
permission gate, since the served claude has no TTY for stdin. The
operator's auth boundary is the bearer API key (DEVCELL_API_KEY).

Environment:

    DEVCELL_API_KEY              Bearer token (auto-generated if empty)
    PORT                         Listen port (overridden by --port)
    LOG_LEVEL                    debug|info|warn|error (default: warn)
    DEVCELL_LOG_PROMPTS=1        Log full prompt + response bodies at INFO level
                                 (off by default; prompts may contain secrets)
    DEVCELL_SYSTEM_PROMPT        Inline BASE prompt (overridden by --system-prompt)
    DEVCELL_SYSTEM_PROMPT_FILE   Path to a file used as the BASE prompt
                                 (overridden by --system-prompt-file)
    DEVCELL_APPEND_SYSTEM_PROMPT      Inline overlay text
                                 (overridden by --append-system-prompt)
    DEVCELL_APPEND_SYSTEM_PROMPT_FILE Path to a file used as overlay text
                                 (overridden by --append-system-prompt-file)

Two independent layers, each resolved over the same chain:

    BASE    replaces Claude Code's built-in prompt entirely (~10.6 KB of
            tool guidance and safety instructions). Leave it unset to keep
            the built-in prompt.
      1. --system-prompt-file            4. DEVCELL_SYSTEM_PROMPT
      2. --system-prompt                 5. [llm].system_prompt_file
      3. DEVCELL_SYSTEM_PROMPT_FILE      6. [llm].system_prompt

    OVERLAY layers on top of whichever base is in effect; nothing is removed.
      1. --append-system-prompt-file     4. DEVCELL_APPEND_SYSTEM_PROMPT
      2. --append-system-prompt          5. [llm].append_system_prompt_file
      3. DEVCELL_APPEND_SYSTEM_PROMPT_FILE  6. [llm].append_system_prompt

A container-context preamble (bind mounts, host paths, runtime constraints)
is auto-prepended to the OVERLAY. Both layers are written to
.devcell/prompts/<cell>/ and passed to claude as file paths.
Per-request 'instructions' (Responses) / 'system' role (Chat) from
the API body still merge into the user prompt independently.

Examples:

    cell serve
    cell serve --port 9090
    cell serve --system-prompt-file ./SYSTEM.md
    cell serve --system-prompt "You are a backend code assistant for project X."
    DEVCELL_LOG_PROMPTS=1 LOG_LEVEL=info cell serve  # debug a client integration`,
	RunE: runServe,
}

var (
	servePort                   int
	serveSystemPrompt           string
	serveSystemPromptFile       string
	serveAppendSystemPrompt     string
	serveAppendSystemPromptFile string
	serveHTTPS                  bool
	serveDebug                  bool
	serveWorkspace              bool
	serveWorkspaceMock          bool
	serveWorkspaceHost          string
	serveDocker                 bool
	serveStop                   bool
	servePTY                    bool
)

func init() {
	serveCmd.Flags().IntVar(&servePort, "port", serve.DefaultPort, "port to listen on")
	serveCmd.Flags().StringVar(&serveSystemPrompt, "system-prompt", "",
		"BASE prompt passed to claude as --system-prompt-file on every request — "+
			"REPLACES Claude Code's built-in prompt (env: DEVCELL_SYSTEM_PROMPT). "+
			"Composes with per-request `instructions`/`system` from the API body.")
	serveCmd.Flags().StringVar(&serveAppendSystemPrompt, "append-system-prompt", "",
		"text layered on top of the base prompt, passed to claude as "+
			"--append-system-prompt-file (env: DEVCELL_APPEND_SYSTEM_PROMPT). "+
			"Composes with the container context devcell always contributes.")
	serveCmd.Flags().StringVar(&serveAppendSystemPromptFile, "append-system-prompt-file", "",
		"path to a file whose contents are layered on top of the base prompt "+
			"(env: DEVCELL_APPEND_SYSTEM_PROMPT_FILE). Mutually exclusive with --append-system-prompt.")
	serveCmd.Flags().StringVar(&serveSystemPromptFile, "system-prompt-file", "",
		"path to a file whose contents REPLACE Claude Code's built-in prompt "+
			"(env: DEVCELL_SYSTEM_PROMPT_FILE). Mutually exclusive with --system-prompt.")
	serveCmd.Flags().BoolVar(&serveHTTPS, "https", false,
		"serve over HTTPS with an auto-generated self-signed certificate")
	serveCmd.Flags().BoolVar(&serveDebug, "debug", false,
		"log full request headers and response bodies to stderr")
	serveCmd.Flags().BoolVar(&serveWorkspace, "workspace", false,
		"enable MS-TSWP workspace feed for Windows App / MSRDC discovery")
	serveCmd.Flags().BoolVar(&serveWorkspaceMock, "workspace-mock", false,
		"serve 4 hardcoded mock desktop entries instead of Docker enumeration")
	serveCmd.Flags().StringVar(&serveWorkspaceHost, "workspace-host", "",
		"public hostname for .rdp files (fallback: Host header from request)")
	serveCmd.Flags().BoolVar(&serveDocker, "docker", false,
		"run cell serve in a Docker container (detached, with Docker socket)")
	serveCmd.Flags().BoolVar(&serveStop, "stop", false,
		"stop a running daemon")
	serveCmd.Flags().BoolVar(&servePTY, "pty", false,
		"drive claude interactively via PTY instead of spawning `claude -p` per request")
}

func runServe(cmd *cobra.Command, args []string) error {
	telemetry.Track("serve", map[string]any{
		"port":   servePort,
		"https":  serveHTTPS,
		"docker": serveDocker,
		"pty":    servePTY,
		"stop":   serveStop,
	})

	if serveStop {
		return stopServeDaemon()
	}
	if serveDocker {
		return startServeDaemon()
	}

	logLevel := os.Getenv("LOG_LEVEL")
	if logLevel == "" {
		logLevel = "warn"
	}
	logger.Initialize(logLevel, true) // plain text, no colors for server logs

	// Port priority: --port flag > PORT env > default
	if !cmd.Flags().Changed("port") {
		if envPort := os.Getenv("PORT"); envPort != "" {
			if p, err := strconv.Atoi(envPort); err == nil {
				servePort = p
			}
		}
	}

	apiKey := os.Getenv("DEVCELL_API_KEY")
	generated := apiKey == ""
	if generated {
		apiKey = serve.GenerateAPIKey()
	}

	if scanFlag("--dry-run") {
		fmt.Printf("serve: port=%d api_key=%s\n", servePort, apiKey)
		return nil
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	c, err := config.LoadFromOS()
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	cellCfg := cfg.LoadFromOS(c.ConfigDir, c.BaseDir)

	promptOpts := cell.ResolveOpts{
		FlagFile:         serveSystemPromptFile,
		FlagInline:       serveSystemPrompt,
		EnvFile:          os.Getenv("DEVCELL_SYSTEM_PROMPT_FILE"),
		EnvInline:        os.Getenv("DEVCELL_SYSTEM_PROMPT"),
		AppendFlagFile:   serveAppendSystemPromptFile,
		AppendFlagInline: serveAppendSystemPrompt,
		AppendEnvFile:    os.Getenv("DEVCELL_APPEND_SYSTEM_PROMPT_FILE"),
		AppendEnvInline:  os.Getenv("DEVCELL_APPEND_SYSTEM_PROMPT"),
		CellCfg:          cellCfg,
		CfgBaseDir:       c.BaseDir,
	}
	systemPromptFile, err := cell.WriteOverlayPrompt(c, cellCfg, promptOpts)
	if err != nil {
		return fmt.Errorf("system prompt: %w", err)
	}
	basePromptFile, err := cell.WriteBasePrompt(c, promptOpts)
	if err != nil {
		return fmt.Errorf("system prompt: %w", err)
	}

	var executor serve.Executor
	if servePTY {
		ptyExec := serve.NewPTYExecutor("claude")
		defer ptyExec.Close()
		executor = ptyExec
	} else {
		executor = &serve.ShellExecutor{}
	}
	srv := serve.NewServer(executor, servePort)
	srv.SetAPIKey(apiKey)
	srv.SetSystemPromptFile(systemPromptFile)
	srv.SetBasePromptFile(basePromptFile)
	// Off by default. Setting DEVCELL_LOG_PROMPTS=1 makes /v1/chat/completions
	// and /v1/responses log full prompt + response text at INFO level. Useful
	// for debugging client integrations; risky for prod logs because prompts
	// often carry secrets / PII / large pasted content.
	if os.Getenv("DEVCELL_LOG_PROMPTS") == "1" {
		srv.SetLogPrompts(true)
	}
	if serveWorkspace && !serveHTTPS {
		serveHTTPS = true
	}
	if serveHTTPS {
		srv.SetTLS(true)
	}
	if serveDebug {
		srv.SetDebug(true)
	}
	if serveWorkspace {
		srv.SetWorkspace(true, serveWorkspaceMock, serveWorkspaceHost)
	}

	addr, errCh := srv.Start(ctx)
	if addr == "" {
		return <-errCh
	}

	scheme := "http"
	if serveHTTPS {
		scheme = "https"
	}
	fmt.Fprintf(os.Stderr, "devcell serve listening on %s://%s\n", scheme, addr)
	if serveHTTPS {
		fmt.Fprintf(os.Stderr, "TLS: self-signed certificate — download PEM: %s://%s/cert\n", scheme, addr)
		if httpAddr := srv.HTTPAddr(); httpAddr != "" {
			fmt.Fprintf(os.Stderr, "HTTP (cert download): http://%s/cert\n", httpAddr)
		}
	}
	if serveWorkspace {
		fmt.Fprintf(os.Stderr, "Workspace feed: %s://%s/RDWeb/Feed/webfeed.aspx\n", scheme, addr)
	}
	if generated {
		fmt.Fprintf(os.Stderr, "API key: %s\n", apiKey)
	}

	return <-errCh
}

const serveContainerName = "cell-serve"

func startServeDaemon() error {
	ctx := context.Background()

	// Check if already running
	out, err := exec.CommandContext(ctx, "docker", "inspect", "--format", "{{.State.Status}}", serveContainerName).Output()
	if err == nil && strings.TrimSpace(string(out)) == "running" {
		return fmt.Errorf("daemon already running (container %s)", serveContainerName)
	}
	// Remove stale container
	exec.CommandContext(ctx, "docker", "rm", "-f", serveContainerName).Run()

	image := docker.PickImageTag(false)

	self, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable: %w", err)
	}

	var args []string
	args = append(args, "run", "-d",
		"--name", serveContainerName,
		"--restart", "unless-stopped",
		"-v", "/var/run/docker.sock:/var/run/docker.sock",
		"-v", self+":/opt/devcell/.local/bin/cell:ro",
		"-p", strconv.Itoa(servePort)+":"+strconv.Itoa(servePort),
	)
	if serveHTTPS {
		httpPort := servePort - 1
		args = append(args, "-p", strconv.Itoa(httpPort)+":"+strconv.Itoa(httpPort))
	}
	args = append(args, "--network", "devcell-network")

	args = append(args, image, "cell", "serve",
		"--port", strconv.Itoa(servePort),
	)
	if serveHTTPS {
		args = append(args, "--https")
	}
	if serveDebug {
		args = append(args, "--debug")
	}
	if serveWorkspace {
		args = append(args, "--workspace")
	}
	if serveWorkspaceMock {
		args = append(args, "--workspace-mock")
	}
	if serveWorkspaceHost != "" {
		args = append(args, "--workspace-host", serveWorkspaceHost)
	}

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker run: %w", err)
	}

	fmt.Fprintf(os.Stderr, "serve container started (container %s)\n", serveContainerName)
	fmt.Fprintf(os.Stderr, "  logs: docker logs -f %s\n", serveContainerName)
	fmt.Fprintf(os.Stderr, "  stop: cell serve --stop\n")
	return nil
}

func stopServeDaemon() error {
	cmd := exec.Command("docker", "stop", serveContainerName)
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("stop %s: %w", serveContainerName, err)
	}
	exec.Command("docker", "rm", serveContainerName).Run()
	fmt.Fprintf(os.Stderr, "serve container stopped (container %s)\n", serveContainerName)
	return nil
}
