# Code generated by hmoptgen from internal/cfg.CellConfig; DO NOT EDIT.
# Regenerate: task hm:generate (runs automatically as a dep of cell:build).
# Each leaf mirrors one devcell.toml key; null (the default) omits the key.
{ lib }:
let
  inherit (lib) mkOption types;
  opt = type: mkOption {
    type = types.nullOr type;
    default = null;
  };
in
{
  cell = {
    image_tag = opt types.str;
    registry = opt types.str;
    gui = opt types.bool;
    timezone = opt types.str;
    locale = opt types.str;
    stack = opt types.str;
    modules = opt (types.listOf types.str);
    nixhome = opt types.str;
    os = opt types.str;
    engine = opt types.str;
    vagrant_provider = opt types.str;
    vagrant_box = opt types.str;
    kvm = opt types.bool;
    per_cell_image = opt types.bool;
    hostname = opt types.str;
    mac_address = opt types.str;
    thin = opt types.bool;
    stale_warning = opt types.bool;
    background = opt types.bool;
    tart_ssh_port = opt types.int;
    tart_ssh_host = opt types.str;
    tart_ssh_user = opt types.str;
    tart_ssh_key = opt types.str;
    tart_oci_image = opt types.str;
    qemu_ssh_port = opt types.int;
    qemu_ssh_host = opt types.str;
    qemu_windows_iso = opt types.str;
    qemu_cpus = opt types.int;
    qemu_memory_gb = opt types.int;
    qemu_disk_size_gb = opt types.int;
    qemu_display = opt types.str;
    libvirt_uri = opt types.str;
    libvirt_path_map = opt (types.attrsOf types.str);
    qemu_project_sync = opt types.str;
    default_command = opt types.str;
    flake = opt types.bool;
    volumes = opt (types.listOf types.str);
  };
  docker = {
    privileged = opt types.bool;
    cap_add = opt (types.listOf types.str);
    mem_limit = opt types.str;
    cpu_limit = opt types.str;
    shm_size = opt types.str;
  };
  build = {
    memory = opt types.str;
    cpus = opt types.str;
    max_jobs = opt types.int;
    cores = opt types.int;
    threads = opt types.int;
  };
  nix = {
    image = opt types.str;
    nixhome = opt types.str;
  };
  llm = {
    system_prompt = opt types.str;
    system_prompt_file = opt types.str;
    append_system_prompt = opt types.str;
    append_system_prompt_file = opt types.str;
    use_ollama = opt types.bool;
    use_openrouter = opt types.bool;
    models = {
      default = opt types.str;
      providers = opt (types.attrsOf (types.submodule {
        options = {
          base_url = opt types.str;
          models = opt (types.listOf types.str);
        };
      }));
    };
  };
  git = {
    author_name = opt types.str;
    author_email = opt types.str;
    committer_name = opt types.str;
    committer_email = opt types.str;
  };
  ports = {
    forward = opt (types.listOf types.str);
    publish_ip = opt types.str;
  };
  op = {
    documents = opt (types.listOf types.str);
    items = opt (types.listOf types.str);
  };
  aws = {
    read_only = opt types.bool;
  };
  mcp = {
    enabled = opt (types.listOf types.str);
  };
  stealth = {
    arch = opt types.str;
    platform = opt types.str;
  };
  gui = {
    enabled = opt types.bool;
    wm = opt types.str;
    resolution = opt types.str;
    scale = opt types.int;
  };
  env = opt (types.attrsOf types.str);
  mise = opt (types.attrsOf types.str);
  volumes = opt (types.listOf (types.submodule {
    options = {
      mount = opt types.str;
    };
  }));
  packages = {
    npm = opt (types.attrsOf types.str);
    python = opt (types.attrsOf types.str);
    nix = {
      stable = opt (types.listOf types.str);
      unstable = opt (types.listOf types.str);
      edge = opt (types.listOf types.str);
    };
  };
  wireguard = opt (types.listOf (types.submodule {
    options = {
      name = opt types.str;
      enabled = opt types.bool;
      config = opt types.str;
    };
  }));
}
